version: '3.8'

services:
  # オンラインビンゴバックエンド
  bingo-backend:
    build: ./backend
    container_name: online-bingo-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bingo-network

  # Caddy（リバースプロキシ）
  caddy:
    image: caddy:2-alpine
    container_name: online-bingo-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frontend:/usr/share/caddy:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      bingo-backend:
        condition: service_healthy
    networks:
      - bingo-network

networks:
  bingo-network:
    driver: bridge

volumes:
  caddy_data:
    external: false
  caddy_config:
    external: false
